# flake8: noqa
# Ignore line length

unscored_sections = [
    {
        "id": "expression_of_interest",
        "name": "Expression of interest",
        "sub_criteria": [
            {
                "id": "applicants_reponse",
                "name": "Applicant's response",
                "themes": [
                    {
                        "id": "cof-eoi-asset",
                        "name": "About your assset",
                        "answers": [
                            {
                                "field_id": "eEaDGz",
                                "form_name": "cof-eoi-asset",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Does your organisation plan both to receive the funding and run the project?",
                            },
                            {
                                "field_id": "dnqIdW",
                                "form_name": "cof-eoi-asset",
                                "field_type": "ukAddressField",
                                "presentation_type": "address",
                                "question": "Address of the asset",
                            },
                            {
                                "field_id": "lLQmNb",
                                "form_name": "cof-eoi-asset",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Is the asset at risk?",
                            },
                            {
                                "field_id": "ilMbMH",
                                "form_name": "cof-eoi-asset",
                                "field_type": "checkboxesField",
                                "presentation_type": "list",
                                "question": "What is the risk to the asset?",
                            },
                            {
                                "field_id": "fBhSNc",
                                "form_name": "cof-eoi-asset",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Has the asset ever been used by or had significance to the community?",
                            },
                            {
                                "field_id": "cPcZos",
                                "form_name": "cof-eoi-asset",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Do you already own the asset?",
                            },
                            {
                                "field_id": "XuAyrs",
                                "form_name": "cof-eoi-asset",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Does the asset belong to a public authority?",
                            },
                            {
                                "field_id": "oDhZlw",
                                "form_name": "cof-eoi-asset",
                                "field_type": "radiosField",
                                "presentation_type": "text",
                                "question": "Stage purchasing asset",
                            },
                        ],
                    },
                    {
                        "id": "cof-eoi-details",
                        "name": "Organisation details",
                        "answers": [
                            {
                                "field_id": "SMRWjl",
                                "form_name": "cof-eoi-details",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Organisation name",
                            },
                            {
                                "field_id": "SxkwhF",
                                "form_name": "cof-eoi-details",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Does your organisation have any alternative names?",
                            },
                            {
                                "field_id": "OpeSdM",
                                "form_name": "cof-eoi-details",
                                "field_type": "ukAddressField",
                                "presentation_type": "address",
                                "question": "Organisation address",
                            },
                            {
                                "field_id": "uYiLsv",
                                "form_name": "cof-eoi-details",
                                "field_type": "radiosField",
                                "presentation_type": "text",
                                "question": "Organisation classification",
                            },
                            {
                                "field_id": "NcQSbU",
                                "form_name": "cof-eoi-details",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Is your organisation subject to any insolvency actions?",
                            },
                            {
                                "field_id": "qkNYMP",
                                "form_name": "cof-eoi-details",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Alternative name 1",
                            },
                            {
                                "field_id": "mVxvon",
                                "form_name": "cof-eoi-details",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Alternative name 2",
                            },
                            {
                                "field_id": "DaIVVm",
                                "form_name": "cof-eoi-details",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Alternative name 3",
                            },
                        ],
                    },
                    {
                        "id": "cof-eoi-funding",
                        "name": "Your funding request",
                        "answers": [
                            {
                                "field_id": "aocRmv",
                                "form_name": "cof-eoi-funding",
                                "field_type": "checkboxesField",
                                "presentation_type": "list",
                                "question": "What do you plan to use COF's funding for?",
                            },
                            {
                                "field_id": "foQgiy",
                                "form_name": "cof-eoi-funding",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Will the leasehold have at least 15 years when your organisation submits a full application?",
                            },
                            {
                                "field_id": "fZAMFv",
                                "form_name": "cof-eoi-funding",
                                "field_type": "numberField",
                                "presentation_type": "integer",
                                "question": "How much capital funding are you requesting from COF?",
                            },
                            {
                                "field_id": "oblxxv",
                                "form_name": "cof-eoi-funding",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Do you plan to request any revenue funding?",
                            },
                            {
                                "field_id": "eOWKoO",
                                "form_name": "cof-eoi-funding",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Do you plan to secure match funding?",
                            },
                            {
                                "field_id": "BykoQQ",
                                "form_name": "cof-eoi-funding",
                                "field_type": "checkboxesField",
                                "presentation_type": "list",
                                "question": "In-kind match funding",
                            },
                            {
                                "field_id": "qgytim",
                                "form_name": "cof-eoi-funding",
                                "field_type": "checkboxesField",
                                "presentation_type": "list",
                                "question": "Cash match funding",
                            },
                            {
                                "field_id": "daJkaD",
                                "form_name": "cof-eoi-funding",
                                "field_type": "checkboxesField",
                                "presentation_type": "list",
                                "question": "Or",
                            },
                            {
                                "field_id": "yZxdeJ",
                                "form_name": "cof-eoi-funding",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Does your project include an element of housing?",
                            },
                            {
                                "field_id": "UORyaF",
                                "form_name": "cof-eoi-funding",
                                "field_type": "radiosField",
                                "presentation_type": "text",
                                "question": "Will you need planning permission for your project?",
                            },
                            {
                                "field_id": "jICagT",
                                "form_name": "cof-eoi-funding",
                                "field_type": "radiosField",
                                "presentation_type": "text",
                                "question": "What stage are you at in securing planning permission?",
                            },
                            {
                                "field_id": "kWRuac",
                                "form_name": "cof-eoi-funding",
                                "field_type": "radiosField",
                                "presentation_type": "text",
                                "question": "What progress have you made to secure this funding?",
                            },
                        ],
                    },
                    {
                        "id": "cof-eoi-support",
                        "name": "Development support provider",
                        "answers": [
                            {
                                "field_id": "iXmKyq",
                                "form_name": "cof-eoi-support",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Do you wish to be contacted by the development support provider, if eligible for in-depth support?",
                            },
                            {
                                "field_id": "ObIBSx",
                                "form_name": "cof-eoi-support",
                                "field_type": "freeTextField",
                                "presentation_type": "free_text",
                                "question": "What are the main things you feel you need support with to submit a good COF application?",
                            },
                            {
                                "field_id": "MxzEYq",
                                "form_name": "cof-eoi-support",
                                "field_type": "freeTextField",
                                "presentation_type": "free_text",
                                "question": "Describe your project and its aims",
                            },
                            {
                                "field_id": "xWnVof",
                                "form_name": "cof-eoi-support",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Name of lead contact",
                            },
                            {
                                "field_id": "NQoGIm",
                                "form_name": "cof-eoi-support",
                                "field_type": "emailAddressField",
                                "presentation_type": "text",
                                "question": "Lead contact email address",
                            },
                            {
                                "field_id": "srxZmv",
                                "form_name": "cof-eoi-support",
                                "field_type": "telephoneNumberField",
                                "presentation_type": "text",
                                "question": "Lead contact telephone number",
                            },
                        ],
                    },
                ],
            }
        ],
    }
]
