# flake8: noqa
# Ignore line length

unscored_sections = [
    {
        "id": "unscored",
        "name": "Unscored",
        "sub_criteria": [
            {
                "id": "organisation_information",
                "name": "Organisation information",
                "themes": [
                    {
                        "id": "general_information",
                        "name": "General information",
                        "answers": [
                            {
                                "field_id": "WWWWxy",
                                "form_name": "organisation-information-cof",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Your unique tracker number",
                            },
                            {
                                "field_id": "YdtlQZ",
                                "form_name": "organisation-information-cof",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Organisation name",
                            },
                            {
                                "field_id": "iBCGxY",
                                "form_name": "organisation-information-cof",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Does your organisation use any other names?",
                            },
                            {
                                "field_id": "PHFkCs",
                                "form_name": "organisation-information-cof",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Alternative names of your organisation - Alternative name 1",
                            },
                            {
                                "field_id": "QgNhXX",
                                "form_name": "organisation-information-cof",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Alternative names of your organisation - Alternative name 2 (optional)",
                            },
                            {
                                "field_id": "XCcqae",
                                "form_name": "organisation-information-cof",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Alternative names of your organisation - Alternative name 3 (optional)",
                            },
                            {
                                "field_id": "GvPSna",
                                "form_name": "organisation-information-cof",
                                "field_type": "radiosField",
                                "presentation_type": "text",
                                "question": "Which regulatory body is your company registered with?",
                            },
                            {
                                "field_id": "zsbmRx",
                                "form_name": "organisation-information-cof",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Which regulatory body is your company registered with? (Other)",
                            },
                            {
                                "field_id": "lajFtB",
                                "form_name": "organisation-information-cof",
                                "field_type": "radiosField",
                                "presentation_type": "text",
                                "question": "What is your organisation type",
                            },
                            {
                                "field_id": "plmwJv",
                                "form_name": "organisation-information-cof",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "What is your organisation type (Other)",
                            },
                            {
                                "field_id": "GlPmCX",
                                "form_name": "organisation-information-cof",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Company registration number",
                            },
                            {
                                "field_id": "RzJfsD",
                                "form_name": "organisation-information-cof",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Does your organisation use any other names?",
                            },
                            {
                                "field_id": "aHIGbK",
                                "form_name": "organisation-information-cof",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Charity number",
                            },
                            {
                                "field_id": "DwfHtk",
                                "form_name": "organisation-information-cof",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Is your organisation a trading subsidiary of a parent company?",
                            },
                            {
                                "field_id": "MPNlZx",
                                "form_name": "organisation-information-cof",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Name of parent organisation",
                            },
                            {
                                "field_id": "MyiYMw",
                                "form_name": "organisation-information-cof",
                                "field_type": "datePartsField",
                                "presentation_type": "text",
                                "question": "Date parent organisation was established",
                            },
                            {
                                "field_id": "ZQolYb",
                                "form_name": "organisation-information-cof",
                                "field_type": "ukAddressField",
                                "presentation_type": "address",
                                "question": "Organisation address",
                            },
                            {
                                "field_id": "zsoLdf",
                                "form_name": "organisation-information-cof",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Is your correspondence address different to the organisation address?",
                            },
                            {
                                "field_id": "VhkCbM",
                                "form_name": "organisation-information-cof",
                                "field_type": "ukAddressField",
                                "presentation_type": "address",
                                "question": "Correspondence address",
                            },
                            {
                                "field_id": "FhbaEy",
                                "form_name": "organisation-information-cof",
                                "field_type": "websiteField",
                                "presentation_type": "text",
                                "question": "Website and social media",
                            },
                            {
                                "field_id": "FcdKlB",
                                "form_name": "organisation-information-cof",
                                "field_type": "websiteField",
                                "presentation_type": "text",
                                "question": "Website and social media - Link or username 2 (optional)",
                            },
                            {
                                "field_id": "BzxgDA",
                                "form_name": "organisation-information-cof",
                                "field_type": "websiteField",
                                "presentation_type": "text",
                                "question": "Website and social media - Link or username 3 (optional)",
                            },
                        ],
                    },
                    {
                        "id": "activities",
                        "name": "Activities",
                        "answers": [
                            {
                                "field_id": "emVGxS",
                                "form_name": "organisation-information-cof",
                                "field_type": "freeTextField",
                                "presentation_type": "free_text",
                                "question": "What is your organisation's main purpose?",
                            },
                            {
                                "field_id": "btTtIb",
                                "form_name": "organisation-information-cof",
                                "field_type": "freeTextField",
                                "presentation_type": "free_text",
                                "question": "Tell us about your organisation's main activities",
                            },
                            {
                                "field_id": "SkocDi",
                                "form_name": "organisation-information-cof",
                                "field_type": "freeTextField",
                                "presentation_type": "free_text",
                                "question": "Tell us about your organisation's main activities - Activity 2 (optional)",
                            },
                            {
                                "field_id": "CNeeiC",
                                "form_name": "organisation-information-cof",
                                "field_type": "freeTextField",
                                "presentation_type": "free_text",
                                "question": "Tell us about your organisation's main activities - Activity 3 (optional)",
                            },
                        ],
                    },
                    {
                        "id": "partnerships",
                        "name": "Partnerships",
                        "answers": [
                            {
                                "field_id": "hnLurH",
                                "form_name": "organisation-information-cof",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Is your application a joint bid in partnership with other organisations?",
                            },
                            {
                                "field_id": "APSjeB",
                                "form_name": "organisation-information-cof",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Partner organisation name",
                            },
                            {
                                "field_id": "biTJjF",
                                "form_name": "organisation-information-cof",
                                "field_type": "ukAddressField",
                                "presentation_type": "address",
                                "question": "Partner organisation address",
                            },
                            {
                                "field_id": "IkmvEt",
                                "form_name": "organisation-information-cof",
                                "field_type": "freeTextField",
                                "presentation_type": "free_text",
                                "question": "Tell us about your partnership and how you plan to work together",
                            },
                            {
                                "field_id": "HYsezC",
                                "form_name": "organisation-information-cof",
                                "field_type": "freeTextField",
                                "presentation_type": "free_text",
                                "question": "Tell us about any partnerships you've formed, and how they'll help the project be successful",
                            },
                        ],
                    },
                ],
            },
            {
                "id": "applicant_information",
                "name": "Applicant information",
                "themes": [
                    {
                        "id": "contact_information",
                        "name": "Contact information",
                        "answers": [
                            {
                                "field_id": "SnLGJE",
                                "form_name": "applicant-information-cof",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Name of lead contact",
                            },
                            {
                                "field_id": "qRDTUc",
                                "form_name": "applicant-information-cof",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Lead contact job title",
                            },
                            {
                                "field_id": "NlHSBg",
                                "form_name": "applicant-information-cof",
                                "field_type": "emailAddressField",
                                "presentation_type": "text",
                                "question": "Lead contact email address",
                            },
                            {
                                "field_id": "FhBkJQ",
                                "form_name": "applicant-information-cof",
                                "field_type": "telephoneNumberField",
                                "presentation_type": "text",
                                "question": "Lead contact telephone number",
                            },
                        ],
                    }
                ],
            },
            {
                "id": "project_information",
                "name": "Project information",
                "themes": [
                    {
                        "id": "previous_funding",
                        "name": "Previous funding",
                        "answers": [
                            {
                                "field_id": "pWwCRM",
                                "form_name": "project-information-cof",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Have you applied to the Community Ownership Fund before?",
                            },
                            {
                                "field_id": "paawsj",
                                "form_name": "project-information-cof",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Was your application successful?",
                            },
                            {
                                "field_id": "ACppgI",
                                "form_name": "project-information-cof",
                                "field_type": "freeTextField",
                                "presentation_type": "free_text",
                                "question": "Describe the project for which you were given funding",
                            },
                            {
                                "field_id": "yuvajR",
                                "form_name": "project-information-cof",
                                "field_type": "numberField",
                                "presentation_type": "currency",
                                "question": "Amount of funding received",
                            },
                        ],
                    },
                    {
                        "id": "project_summary",
                        "name": "Project summary",
                        "answers": [
                            {
                                "field_id": "apGjFS",
                                "form_name": "project-information-cof",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Project name",
                            },
                            {
                                "field_id": "uypCNM",
                                "form_name": "project-information-cof",
                                "field_type": "freeTextField",
                                "presentation_type": "free_text",
                                "question": "Give a brief summary of your project, including what you hope to achieve",
                            },
                            {
                                "field_id": "AgeRbd",
                                "form_name": "project-information-cof",
                                "field_type": "freeTextField",
                                "presentation_type": "free_text",
                                "question": "Tell us about the planned activities and/or services that will take place in the asset",
                            },
                        ],
                    },
                ],
            },
            {
                "id": "asset_information",
                "name": "Asset information",
                "themes": [
                    {
                        "id": "asset_ownership",
                        "name": "Asset ownership",
                        "answers": [
                            {
                                "field_id": "LaxeJN",
                                "form_name": "asset-information-cof",
                                "field_type": "radiosField",
                                "presentation_type": "text",
                                "question": "How do you intend to take community ownership of the asset?",
                            },
                            {
                                "field_id": "tTOrEp",
                                "form_name": "asset-information-cof",
                                "field_type": "clientSideFileUploadField",
                                "presentation_type": "s3bucketPath",
                                "question": "Upload asset valuation or lease agreement",
                                "path": "upload-asset-valuation-or-lease-agreement",
                            },
                            {
                                "field_id": "wAUFqr",
                                "form_name": "asset-information-cof",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Do you know who currently owns your asset?",
                            },
                            {
                                "field_id": "FOURVe",
                                "form_name": "asset-information-cof",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Name of current asset owner",
                            },
                            {
                                "field_id": "apJIBm",
                                "form_name": "asset-information-cof",
                                "field_type": "freeTextField",
                                "presentation_type": "free_text",
                                "question": "Describe the terms of your lease if you have rented the asset",
                            },
                            {
                                "field_id": "XPcbJx",
                                "form_name": "asset-information-cof",
                                "field_type": "freeTextField",
                                "presentation_type": "free_text",
                                "question": "Describe the expected sale process, or the proposed terms of your lease if you are renting the asset",
                            },
                            {
                                "field_id": "jGjScT",
                                "form_name": "asset-information-cof",
                                "field_type": "datePartsField",
                                "presentation_type": "text",
                                "question": "Expected date of sale or lease",
                            },
                            {
                                "field_id": "VGXXyq",
                                "form_name": "asset-information-cof",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Is your asset currently publicly owned?",
                            },
                            {
                                "field_id": "rNYmXq",
                                "form_name": "asset-information-cof",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "Tell us about the person you have spoken to at the relevant public body about the asset",
                            },
                            {
                                "field_id": "MIqglh",
                                "form_name": "asset-information-cof",
                                "field_type": "checkboxesField",
                                "presentation_type": "list",
                                "question": "When you buy or lease a publicly owned asset, the public authority cannot transfer statutory services or duties to the community group.",
                            },
                            {
                                "field_id": "JdEmqn",
                                "form_name": "asset-information-cof-r3-w2",
                                "field_type": "checkboxesField",
                                "presentation_type": "list",
                                "question": "Grants from this fund cannot be used to buy the freehold or premium on the lease of a publicly owned asset. Money must only be used for renovation and refurbishment costs",
                            },
                            {
                                "field_id": "mZwrmI",
                                "form_name": "asset-information-cof",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Are there assets or services of a similar type available locally?",
                            },
                            {
                                "field_id": "BfgLCc",
                                "form_name": "asset-information-cof",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Is your asset different from what is available locally?",
                            },
                            {
                                "field_id": "GEJNWF",
                                "form_name": "asset-information-cof",
                                "field_type": "freeTextField",
                                "presentation_type": "free_text",
                                "question": "How accessible is the closest asset or service?",
                            },
                            {
                                "field_id": "WTZoVD",
                                "form_name": "asset-information-cof",
                                "field_type": "freeTextField",
                                "presentation_type": "free_text",
                                "question": "Tell us how and why your asset or the service is different",
                            },
                            {
                                "field_id": "CFFsxV",
                                "form_name": "asset-information-cof",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Does part of your project include a commercial aspect?",
                            },
                            {
                                "field_id": "FDZQTQ",
                                "form_name": "asset-information-cof",
                                "field_type": "freeTextField",
                                "presentation_type": "free_text",
                                "question": "Tell us how the commercial aspect relates to the other services you provide",
                            },
                        ],
                    },
                    {
                        "id": "asset_evidence",
                        "name": "Asset evidence",
                        "answers": [
                            {
                                "field_id": "RFTloT",
                                "form_name": "asset-information-cof",
                                "field_type": "clientSideFileUploadField",
                                "presentation_type": "s3bucketPath",
                                "question": "Upload public ownership evidence",
                                "path": "public-ownership-details-and-declarations",
                            },
                        ],
                    },
                    {
                        "id": "asset_background",
                        "name": "Asset background",
                        "answers": [
                            {
                                "field_id": "oXGwlA",
                                "form_name": "asset-information-cof",
                                "field_type": "radiosField",
                                "presentation_type": "text",
                                "question": "Asset type",
                            },
                            {
                                "field_id": "aJGyCR",
                                "form_name": "asset-information-cof",
                                "field_type": "radiosField",
                                "presentation_type": "text",
                                "question": "Asset type (Other)",
                            },
                            {
                                "field_id": "QPIPjx",
                                "form_name": "asset-information-cof",
                                "field_type": "datePartsField",
                                "presentation_type": "text",
                                "question": "When was the asset listed?",
                            },
                            {
                                "field_id": "OJWGGr",
                                "form_name": "asset-information-cof",
                                "field_type": "websiteField",
                                "presentation_type": "text",
                                "question": "Provide a link to the listing",
                            },
                            {
                                "field_id": "iqnlTk",
                                "form_name": "asset-information-cof",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Is this a registered Asset of Community Value (ACV)?",
                            },
                        ],
                    },
                    {
                        "id": "asset_location",
                        "name": "Asset location",
                        "answers": [
                            {
                                "field_id": "EfdliG",
                                "form_name": "project-information-cof",
                                "field_type": "ukAddressField",
                                "presentation_type": "address",
                                "question": "Address of the community asset",
                            },
                            {
                                "field_id": "fIEUcb",
                                "form_name": "project-information-cof",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "In which constituency is your asset?",
                            },
                            {
                                "field_id": "SWfcTo",
                                "form_name": "project-information-cof",
                                "field_type": "textField",
                                "presentation_type": "text",
                                "question": "In which local council area is your asset?",
                            },
                        ],
                    },
                ],
            },
            {
                "id": "business-plan",
                "name": "Business plan",
                "themes": [
                    {
                        "id": "business_plan",
                        "name": "Business plan",
                        "answers": [
                            {
                                "field_id": "ndpQJk",
                                "form_name": "upload-business-plan-cof",
                                "field_type": "clientSideFileUploadField",
                                "presentation_type": "s3bucketPath",
                                "question": "Business plan for your project (document upload)",
                                "path": "your-business-plan",
                            },
                        ],
                    }
                ],
            },
        ],
    },
    {
        "id": "declarations",
        "name": "Declarations",
        "sub_criteria": [
            {
                "id": "declarations",
                "name": "Declarations",
                "themes": [
                    {
                        "id": "declarations",
                        "name": "Declarations",
                        "answers": [
                            {
                                "field_id": "vSQKwD",
                                "form_name": "declarations-cof",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Confirm you have considered subsidy control and state aid implications for your project, and the information you have given us is correct",
                            },
                            {
                                "field_id": "CQoLFp",
                                "form_name": "declarations-cof",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Confirm you have considered people with protected characteristics throughout the planning of your project",
                            },
                            {
                                "field_id": "jdPkiX",
                                "form_name": "declarations-cof",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Confirm you have considered sustainability and the environment throughout the planning of your project, including compliance with the government's Net Zero ambitions",
                            },
                            {
                                "field_id": "qWuSCy",
                                "form_name": "declarations-cof",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Confirm you have a bank account set up and associated with the organisation you are applying on behalf of",
                            },
                            {
                                "field_id": "tjZlml",
                                "form_name": "declarations-cof",
                                "field_type": "yesNoField",
                                "presentation_type": "text",
                                "question": "Confirm that the information you've provided in this application is accurate to the best of your knowledge on the date of submission",
                            },
                        ],
                    },
                ],
            },
        ],
    },
]
