"""empty message

Revision ID: 61af96c8345b
Revises: 4bdc171458b2
Create Date: 2023-07-10 14:59:29.834936

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "61af96c8345b"
down_revision = "fd9cd5862227"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag", schema=None) as b_op:
        b_op.drop_constraint("uq_tag_value_round_id", type_="unique")
        b_op.execute(
            sa.text(
                "CREATE UNIQUE INDEX value_round_id_unique_idx ON tag (lower(value), round_id)"
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tag", schema=None) as b_op:
        b_op.drop_index("value_round_id_unique_idx")
        b_op.create_unique_constraint(
            "uq_tag_value_round_id", ["value", "round_id"]
        )
    # ### end Alembic commands ###
