openapi: "3.0.0"
info:
  description: Assessment API for DLUHC Funding Service Design
  version: "1.0.0"
  title: Funding Service Design - Assessment Store
tags:
  - name: assessments
    description: Assessment operations
  - name: scores
    description: Score operations

paths:
  '/application_overviews/{fund_id}/{round_id}':
    parameters:
    - name: fund_id
      in: path
      required: true
      schema:
        type: string
        format: path
    - name: round_id
      in: path
      required: true
      schema:
        type: string
        format: path
    - name: search_term
      in: query
      style: form
      schema:
        type: string
        format: query
      required: false
      explode: true
    - name: asset_type
      in: query
      style: form
      schema:
        type: string
        format: query
      required: false
      explode: true
    - name: status
      in: query
      style: form
      schema:
        type: string
        format: query
      required: false
      explode: true
    get:
      tags:
        - assessments
      summary: Search assessments
      description: List all assessments
      operationId: api.routes.all_assessments_for_fund_round_id
      responses:
        200:
          description: SUCCESS - A list of assessments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'components.yml#/components/schemas/Assessment'

  '/score':
    get:
      tags:
        - scores
      summary: get score for subcriteria in application
      description: get a score for a subcriteria in an application
      operationId: api.routes.latest_score_for_application_sub_criteria
      responses:
        200:
          description: SUCCESS - Score for Subcriteria in Application
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: 'components.yml#/components/schemas/Score'
      parameters:
      - name: application_id
        in: query
        schema:
          type: string
        required: true
      - name: sub_criteria_id
        in: query
        schema:
          type: string
        required: true
      - name: score
        in: query
        schema:
          type: integer
        required: false
      - name: justification
        in: query
        schema:
          type: string
        required: false
      - name: date_created
        in: query
        schema:
          type: string
        required: false
      - name: user_id
        in: query
        schema:
          type: string
        required: false
    post:
      tags:
        - scores
      summary: post score for subcriteria in application
      description: post a score for a subcriteria in an application
      operationId: api.routes.post_score_for_application_sub_criteria
      requestBody:
        description: Score creation parameters
        required: true
        content:
          application/json:
            schema:
              $ref: 'components.yml#/components/schemas/PostScore'
            example:
              score: 3
              justification: 'bang average'
              application_id: 'r3p1ac33-7412-4991-c4t1-c41cbf4d3bbd'
              sub_criteria_id: 'app-info'
              user_id: 'gio'
      responses:
        201:
          description: SUCCESS - Score for Subcriteria in Application Submitted
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: 'components.yml#/components/schemas/Score'
        401:
          description: ERROR - Could not Save Score
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/Error'
              example:
                code: 401
                status: 'error'
                message: 'Could not save Score for application sub-criteria'

  '/sub_criteria_overview/{sub_criteria_id}':
    parameters:
    - name: sub_criteria_id
      in: path
      required: true
      schema:
        type: string
        format: path
    get:
      tags:
        - assessments
      summary: Sub criteria
      description: Returns sub criteria metadata and themes
      operationId: api.routes.sub_criteria
      responses:
        200:
          description: SUCCESS - A subcriteria
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/SubCriteria'

  '/application_overviews/{application_id}':
    parameters:
    - name: application_id
      in: path
      required: true
      schema:
        type: string
        format: path
    get:
      tags:
        - assessments
      summary: Retrieves data to populate the assessors task list page for a given application
      description: Retrieves data to populate the assessors task list page for a given application
      operationId: api.routes.get_assessor_task_list_state
      responses:
        200:
          description: SUCCESS - Accessor task list state
          content:
            application/json:
              schema:
                type: object
                $ref: 'assessor_task_list.yml#/components/schemas/AssessorTaskListState'

  '/sub_criteria_themes/{application_id}/{theme_id}':
    parameters:
    - name: application_id
      in: path
      required: true
      schema:
        type: string
        format: path
    - name: theme_id
      in: path
      required: true
      schema:
        type: string
        format: path    
    get:
      tags:
        - assessments
      summary: Retrieves data to populate the answers for sub criteria theme
      description: Retrieves data to populate the answers for sub criteria theme
      operationId: api.routes.get_sub_criteria_theme_answers
      responses:
        200:
          description: SUCCESS - Sub criteria themes
          content:
            application/json:
              schema:
                type: array
                $ref: 'components.yml#/components/schemas/Sub_criteria_theme'
              example:
                [
                {
                  "answer": [
                    ["Capital funding","2300"],
                    ["Revenue funding (optional)","2300"]
                  ],
                  "field_id": ["HhhyGh","jhusgT"],
                  "field_type": "numberField",
                  "form_name": "",
                  "presentation_type": "grouped_fields",
                  "question": "Total funding request"
                },
                {
                  "answer": "Capital costs",
                  "field_id": "ThLigF",
                  "field_type": "multiInputField",
                  "form_name": "funding-required",
                  "presentation_type": "heading",
                  "question": "Capital costs"
                },
                {
                  "field_id": "ThLigF",
                  "field_type": "textField",
                  "form_name": "funding-required",
                  "presentation_type": "description",
                  "question": "Describe the cost"
                },
                {
                  "field_id": "ThLigF",
                  "field_type": "numberField",
                  "form_name": "funding-required",
                  "presentation_type": "amount",
                  "question": "Amount"
                },
                {
                  "answer": "2300",
                  "field_id": "fnIdkJ",
                  "field_type": "numberField",
                  "form_name": "funding-required",
                  "presentation_type": "text",
                  "question": "Asset value"
                },
              ]
        500:
          description: "Bad request - Incorrect application_id or theme_id"
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/GeneralError'                
       
