openapi: "3.0.0"
info:
  description: Assessment API for DLUHC Funding Service Design
  version: "1.0.0"
  title: Funding Service Design - Assessment Store
tags:
  - name: assessments
    description: Assessment operations

paths:
  /assessments:
    get:
      tags:
        - assessments
      summary: Search assessments
      description: List all assessments
      operationId: api.AssessmentsView.search
      responses:
        200:
          description: SUCCESS - A list of assessments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'components.yml#/components/schemas/Assessment'
    post:
      tags:
        - assessments
      summary: Register an assessment
      description: Register a new application for assessment
      operationId: api.AssessmentsView.register
      requestBody:
        description: Assessment registration parameters
        required: true
        content:
          application/json:
            schema:
              $ref: 'components.yml#/components/schemas/AssessmentCreate'
            example:
              applicationId: 'abc'
      responses:
        201:
          description: SUCCESS - Application registered, assessment created
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/Assessment'
        401:
          description: ERROR - Could not create assessment
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/GeneralError'
              example:
                code: 401
                status: 'error'
                message: 'An assessment for this application already exists'
  '/assessments/{assessment_id}':
    get:
      tags:
        - assessments
      summary: Get an assessment
      description: Return an assesment
      operationId: api.AssessmentsView.get
      responses:
        200:
          description: SUCCESS - Assessment returned
          content:
              application/json:
                schema:
                  $ref: 'components.yml#/components/schemas/Assessment'
        404:
          description: ERROR - Assessment not found
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/GeneralError'
              example:
                code: 404
                status: 'error'
                message: 'Assessment could not be found'
      parameters:
        - name: assessment_id
          in: path
          required: true
          schema:
            type: string
            format: path

  '/update-compliance':
    post:
      tags:
        - assessment status
      summary: Update assessment status
      description: Return an updated assessment status
      operationId: api.AssessmentsView.status
      requestBody:
        description: Assessment status parameters
        required: true
        content:
          application/json:
            schema:
              $ref: 'components.yml#/components/schemas/UpdateStatus'
            example:
              id: '12h6-456j'
              compliance_status: 'COMPLIANT'
      responses:
        200:
          description: SUCCESS - Assessment status returned
          content:
              application/json:
                schema:
                  $ref: 'components.yml#/components/schemas/Assessment'

        404:
          description: ERROR - Assessment not found
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/GeneralError'
              example:
                code: 404
                status: 'error'
                message: 'Assessment could not be found'

  '/assessments/{assessment_id}/sub_criterias':
    get:
      tags:
        - sub_criteria
      summary: Get list of sub_criterias
      description: Get list of sub_criterias
      operationId: api.SubCriteriaView.list
      responses:
        200:
          description: SUCCESS - A list of sub_criterias
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'components.yml#/components/schemas/SubCriteria'
      parameters:
        - name: assessment_id
          in: path
          required: true
          schema:
            type: string
            format: path

  '/assessments/{assessment_id}/sub_criterias/{sub_criteria_id}':
    get:
      tags:
        - sub_criteria
      summary: Get sub_criteria by ID
      description: Get sub_criteria by ID
      operationId: api.SubCriteriaView.get
      responses:
        200:
          description: SUCCESS - the sub_criteria searched for
          content:
            application/json:
              schema:
                  $ref: 'components.yml#/components/schemas/SubCriteria'
        404:
          description: "sub_criteria not found."
          content:
              texts/plain:
                schema:
                  $ref: 'components.yml#/components/schemas/Error'
      parameters:
        - name: assessment_id
          in: path
          required: true
          schema:
            type: string
            format: path
        - name: sub_criteria_id
          in: path
          required: true
          schema:
            type: string
            format: path

  '/assessments/{assessment_id}/sub_criterias/{sub_criteria_id}/scores':
    get:
      tags:
        - scores_justifications
      summary: Get scores and justifications
      description: Get scores and justifications for given assessment and sub_criteria
      operationId: api.ScoresJustificationsView.get
      responses:
        200:
          description: SUCCESS - scores for sub_criteria for assessment
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'components.yml#/components/schemas/ScoreJustification'
      parameters:
        - name: assessment_id
          in: path
          required: true
          schema:
            type: string
            format: path
        - name: sub_criteria_id
          in: path
          required: true
          schema:
            type: string
            format: path
    post:
      tags:
        - scores_justifications
      summary: Register a score and justification
      description: Register a score and jsutification for an application
      operationId: api.ScoresJustificationsView.post
      requestBody:
        description: scores_justifications registration parameters
        required: true
        content:
          application/json:
            schema:
              $ref: 'components.yml#/components/schemas/ScoreJustification'
            example:
              score: 5
              justification: 'wow'
              person_id: 'person_1'
      responses:
        201:
          description: SUCCESS - Score and justification registered
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/ScoreJustification'
        401:
          description: ERROR - Could not register score and justification
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/Error'
              example:
                code: 401
                status: 'error'
                message: 'A score and justification for this application already exists'
      parameters:
        - name: assessment_id
          in: path
          required: true
          schema:
            type: string
            format: path
        - name: sub_criteria_id
          in: path
          required: true
          schema:
            type: string
            format: path

  '/assessments/{assessment_id}/sub_criterias/{sub_criteria_id}/compliance':
    get:
      tags:
        - compliance
      summary: Get compliance
      description: Get compliance status for given assessment and sub_criteria
      operationId: api.ComplianceView.get
      responses:
        200:
          description: SUCCESS - compliance for sub_criteria for assessment
          content:
            application/json:
              schema:
                  $ref: 'components.yml#/components/schemas/Compliance'
      parameters:
        - name: assessment_id
          in: path
          required: true
          schema:
            type: string
            format: path
        - name: sub_criteria_id
          in: path
          required: true
          schema:
            type: string
            format: path
    post:
      tags:
        - compliance
      summary: Register a compliance status
      description: Register a compliance status for an application
      operationId: api.ComplianceView.post
      requestBody:
        description: Compliance registration parameters
        required: true
        content:
          application/json:
            schema:
              $ref: 'components.yml#/components/schemas/Compliance'
            example:
              is_compliant: True
      responses:
        201:
          description: SUCCESS - compliance status registered
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/Compliance'
        401:
          description: ERROR - Could not register compliance status
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/Error'
              example:
                code: 401
                status: 'error'
                message: 'A compliance status for this application already exists'
      parameters:
        - name: assessment_id
          in: path
          required: true
          schema:
            type: string
            format: path
        - name: sub_criteria_id
          in: path
          required: true
          schema:
            type: string
            format: path
