components:
  schemas:
    Answer:
      type: object
      properties:
        field_id:
          oneOf:
            - type: string
            - type: array
              items:
                type: string
        form_name:
          type: string
        field_type:
          type: string
        presentation_type:
          type: string
        question:
          type: string
    Theme:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        answers:
          type: array
          items:
            $ref: '#/components/schemas/Answer'
    SubCriteria:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        themes:
          type: array
          items:
            $ref: '#/components/schemas/Theme'
    UnscoredCriteria:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        sub_criteria:
          type: array
          items:
            $ref: '#/components/schemas/SubCriteria'
    ScoredCriteria:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        weighting:
          type: number
          format: float
        sub_criteria:
          type: array
          items:
            $ref: '#/components/schemas/SubCriteria'
    Config:
      type: object
      properties:
        schema_id:
          type: string
        unscored_sections:
          type: array
          items:
            $ref: '#/components/schemas/UnscoredCriteria'
        scored_criteria:
          type: array
          items:
            $ref: '#/components/schemas/ScoredCriteria'
