"""empty message

Revision ID: 1508d2c4dfa8
Revises: 5ce0b8e0e1b6
Create Date: 2022-12-02 15:02:26.905696

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1508d2c4dfa8"
down_revision = "5ce0b8e0e1b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scores",
        sa.Column("score_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("justification", sa.Text(), nullable=False),
        sa.Column("application_id", postgresql.UUID(), nullable=True),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("sub_criteria_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["assessment_records.application_id"],
            name=op.f("fk_scores_application_id_assessment_records"),
        ),
        sa.PrimaryKeyConstraint("score_id", name=op.f("pk_scores")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scores")
    # ### end Alembic commands ###
