"""empty message

Revision ID: 17835f3105ca
Revises: 4cf5c9a457d1
Create Date: 2022-07-19 23:37:00.515748

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op


# revision identifiers, used by Alembic.
revision = "17835f3105ca"
down_revision = "4cf5c9a457d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments",
        sa.Column(
            "id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("assessment_id", sa.Text(), nullable=True),
        sa.Column("assessor_user_id", sa.Text(), nullable=True),
        sa.Column("sub_criteria_id", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment.id"],
            name=op.f("fk_comments_assessment_id_assessment"),
        ),
        sa.ForeignKeyConstraint(
            ["sub_criteria_id"],
            ["sub_criteria.id"],
            name=op.f("fk_comments_sub_criteria_id_sub_criteria"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comments")
    # ### end Alembic commands ###
