"""empty message

Revision ID: 1e8a9c717347
Revises: 
Create Date: 2022-11-09 11:12:00.692723

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e8a9c717347'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_records',
    sa.Column('assessment_id', sa.Text(), nullable=False),
    sa.Column('short_id', sa.Text(), nullable=False),
    sa.Column('type_of_application', sa.Text(), nullable=False),
    sa.Column('project_name', sa.Text(), nullable=False),
    sa.Column('funding_amount_requested', sa.Float(), nullable=False),
    sa.Column('round_id', sa.Text(), nullable=False),
    sa.Column('fund_id', sa.Text(), nullable=False),
    sa.Column('langauge', sa.Text(), nullable=False),
    sa.Column('workflow_status', postgresql.ENUM('NOT_STARTED', 'IN_PROGRESS', 'SUBMITTED', 'COMPLETED', name='status'), nullable=False),
    sa.PrimaryKeyConstraint('assessment_id', name=op.f('pk_assessment_records'))
    )
    with op.batch_alter_table('assessment_records', schema=None) as batch_op:
        batch_op.create_index('assessment_records_id_index', ['assessment_id'], unique=False, postgresql_using='hash')
        batch_op.create_index(batch_op.f('ix_assessment_records_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_records_fund_id'), ['fund_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_records_round_id'), ['round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_records_workflow_status'), ['workflow_status'], unique=False)

    op.create_table('application_ingestion_records',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('assessment_record_id', sa.Text(), nullable=True),
    sa.Column('application_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('application_json_sha256', postgresql.BYTEA(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_record_id'], ['assessment_records.assessment_id'], name=op.f('fk_application_ingestion_records_assessment_record_id_assessment_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_ingestion_records'))
    )
    op.create_table('assessment_json_blobs',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('assessment_record_id', sa.Text(), nullable=True),
    sa.Column('jsonb_blob', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['assessment_record_id'], ['assessment_records.assessment_id'], name=op.f('fk_assessment_json_blobs_assessment_record_id_assessment_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_json_blobs'))
    )
    with op.batch_alter_table('assessment_json_blobs', schema=None) as batch_op:
        batch_op.create_index('application_jsonb_index', ['jsonb_blob'], unique=False, postgresql_ops={'application_json': 'jsonb_path_ops'}, postgresql_using='gin')
        batch_op.create_index('assessment_blob_id_index', ['assessment_record_id'], unique=False, postgresql_using='hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_json_blobs', schema=None) as batch_op:
        batch_op.drop_index('assessment_blob_id_index', postgresql_using='hash')
        batch_op.drop_index('application_jsonb_index', postgresql_ops={'application_json': 'jsonb_path_ops'}, postgresql_using='gin')

    op.drop_table('assessment_json_blobs')
    op.drop_table('application_ingestion_records')
    with op.batch_alter_table('assessment_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_records_workflow_status'))
        batch_op.drop_index(batch_op.f('ix_assessment_records_round_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_records_fund_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_records_assessment_id'))
        batch_op.drop_index('assessment_records_id_index', postgresql_using='hash')

    op.drop_table('assessment_records')
    # ### end Alembic commands ###
