"""empty message

Revision ID: 30d27919f1d8
Revises: 3a22407701c8
Create Date: 2023-01-19 10:55:23.151831

"""
import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_extension import PGExtension
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = "30d27919f1d8"
down_revision = "3a22407701c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("flags", schema=None) as batch_op:
        batch_op.alter_column(
            "justification", existing_type=sa.TEXT(), nullable=True
        )
        batch_op.alter_column(
            "section_to_flag", existing_type=sa.TEXT(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("flags", schema=None) as batch_op:
        batch_op.alter_column(
            "section_to_flag", existing_type=sa.TEXT(), nullable=False
        )
        batch_op.alter_column(
            "justification", existing_type=sa.TEXT(), nullable=False
        )

    # ### end Alembic commands ###
