"""empty message

Revision ID: 3a22407701c8
Revises: 99ad87a4f888
Create Date: 2023-01-09 16:06:23.980091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a22407701c8'
down_revision = '99ad87a4f888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("flags","resolution_reason")
    op.execute("DROP TYPE resolutiontype;")
    op.drop_column("flags","flag_type")
    op.execute("DROP TYPE flagtype;")
    flag_enum = postgresql.ENUM("FLAGGED", "STOPPED", "QA_COMPLETED", "RESOLVED", name='flagtype')
    flag_enum.create(op.get_bind())
    op.add_column('flags', sa.Column('flag_type', flag_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("flags","flag_type")
    flag_type_enum = postgresql.ENUM("FLAGGED", "STOPPED", "QA_COMPLETED", name='flagtype')
    flag_type_enum.create(op.get_bind())
    resolution_type_enum = postgresql.ENUM('QUERY_RESOLVED', 'STOP_ASSESSMENT', name='resolutiontype')
    resolution_type_enum.create(op.get_bind())
    op.add_column('flags', sa.Column('resolution_reason', resolution_type_enum, autoincrement=False, nullable=True))
    op.add_column('flags', sa.Column('flag_type', flag_type_enum, autoincrement=False, nullable=False))

    # ### end Alembic commands ###
