"""empty message

Revision ID: 3e44462292c2
Revises: d7eed6243143
Create Date: 2022-10-19 10:54:50.273932

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '3e44462292c2'
down_revision = 'd7eed6243143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('assessment_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('assessor_user_id', sa.Text(), nullable=True),
    sa.Column('sub_criteria_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], name=op.f('fk_comment_assessment_id_assessment')),
    sa.ForeignKeyConstraint(['sub_criteria_id'], ['sub_criteria.id'], name=op.f('fk_comment_sub_criteria_id_sub_criteria')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
