"""empty message

Revision ID: 409915dc382e
Revises: 5ce0b8e0e1b6
Create Date: 2022-11-28 17:09:29.370884

"""
from alembic import op
from alembic_utils.pg_extension import PGExtension

# revision identifiers, used by Alembic.
revision = "409915dc382e"
down_revision = "1508d2c4dfa8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_pg_trgm = PGExtension(schema="public", signature="pg_trgm")
    op.create_entity(public_pg_trgm)

    with op.batch_alter_table("assessment_records", schema=None) as batch_op:
        batch_op.create_index(
            "ix_project_name",
            ["project_name"],
            unique=False,
            postgresql_ops={"project_name": "gin_trgm_ops"},
            postgresql_using="gin",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("assessment_records", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_project_name",
            postgresql_ops={"project_name": "gin_trgm_ops"},
            postgresql_using="gin",
        )

    public_pg_trgm = PGExtension(schema="public", signature="pg_trgm")
    op.drop_entity(public_pg_trgm)

    # ### end Alembic commands ###
