"""empty message

Revision ID: 4bdc171458b2
Revises: 6ad072a15e50
Create Date: 2023-06-30 15:53:26.608073

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "4bdc171458b2"
down_revision = "6ad072a15e50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE status ADD VALUE 'QA_COMPLETED'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE status RENAME TO status_old")
    op.execute(
        "CREATE TYPE status AS ENUM ('NOT_STARTED','IN_PROGRESS','SUBMITTED','COMPLETED')"
    )
    op.execute(
        "ALTER TABLE assessment_records ALTER COLUMN workflow_status TYPE status USING workflow_status::text::status"
    )
    op.execute("DROP TYPE status_old")
    # ### end Alembic commands ###
