"""empty message

Revision ID: 4cf5c9a457d1
Revises: 60775d659a5e
Create Date: 2022-07-19 15:21:00.387864

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op


# revision identifiers, used by Alembic.
revision = "4cf5c9a457d1"
down_revision = "60775d659a5e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "criteria",
        sa.Column(
            "id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("round_id", sa.String(), nullable=True),
        sa.Column("fund_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_criteria")),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("criteria")
    # ### end Alembic commands ###
