"""empty message

Revision ID: 758f28f0427e
Revises: 4dd55a3dc51e
Create Date: 2022-07-08 15:32:40.437062

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy_utils import UUIDType


# revision identifiers, used by Alembic.
revision = "758f28f0427e"
down_revision = "4dd55a3dc51e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sub_criteria",
        sa.Column("sub_criteria_id", sa.Text(), nullable=False),
        sa.Column("round_id", sa.Text(), nullable=True),
        sa.Column("criteria_id", sa.Text(), nullable=True),
        sa.Column("sub_criteria_title", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("sub_criteria_id"),
    )
    op.create_table(
        "comments",
        sa.Column(
            "comments_id",
            UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("assessment_id", sa.Text(), nullable=True),
        sa.Column("person_id", sa.Text(), nullable=True),
        sa.Column("sub_criteria_id", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sub_criteria_id"],
            ["sub_criteria.sub_criteria_id"],
        ),
        sa.PrimaryKeyConstraint("comments_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comments")
    op.drop_table("sub_criteria")
    # ### end Alembic commands ###
