"""empty message

Revision ID: 91e0d528fc9f
Revises: 190bf5378715
Create Date: 2022-11-24 15:52:01.294846

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91e0d528fc9f'
down_revision = '190bf5378715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('just_scores',
    sa.Column('score_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('application_id', postgresql.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sub_criteria_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['assessment_records.application_id'], name=op.f('fk_just_scores_application_id_assessment_records')),
    sa.PrimaryKeyConstraint('score_id', name=op.f('pk_just_scores'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('just_scores')
    # ### end Alembic commands ###
