"""empty message

Revision ID: ac1b335ca36a
Revises: de12e9222848
Create Date: 2022-07-14 16:11:39.558786

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "ac1b335ca36a"
down_revision = "de12e9222848"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assessment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fund_id", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("round_id", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assessment", schema=None) as batch_op:
        batch_op.drop_column("round_id")
        batch_op.drop_column("fund_id")

    # ### end Alembic commands ###
