"""empty message

Revision ID: ae4fda532587
Revises: 
Create Date: 2022-11-04 12:01:13.523263

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae4fda532587'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_records',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('application_id', sa.Text(), nullable=False),
    sa.Column('application_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_records'))
    )
    with op.batch_alter_table('assessment_records', schema=None) as batch_op:
        batch_op.create_index('application_id_index', ['application_id'], unique=False)
        batch_op.create_index('application_json_index', ['application_json'], unique=False, postgresql_ops={'application_json': 'jsonb_path_ops'}, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_records', schema=None) as batch_op:
        batch_op.drop_index('application_json_index', postgresql_ops={'application_json': 'jsonb_path_ops'}, postgresql_using='gin')
        batch_op.drop_index('application_id_index')

    op.drop_table('assessment_records')
    # ### end Alembic commands ###
