"""empty message

Revision ID: ae831f889c9e
Revises: cd404dd517c5
Create Date: 2022-07-15 10:23:34.987578

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op


# revision identifiers, used by Alembic.
revision = "ae831f889c9e"
down_revision = "cd404dd517c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compliance",
        sa.Column(
            "compliance_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("assessment_id", sa.Text(), nullable=True),
        sa.Column("sub_criteria_id", sa.Text(), nullable=True),
        sa.Column("is_compliant", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sub_criteria_id"],
            ["sub_criteria.sub_criteria_id"],
        ),
        sa.PrimaryKeyConstraint("compliance_id"),
    )
    op.add_column(
        "scores_justifications",
        sa.Column("person_id", sa.Text(), nullable=True),
    )
    op.drop_column("scores_justifications", "assessor_user_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scores_justifications",
        sa.Column("assessor_user_id", sa.VARCHAR(length=255), nullable=True),
    )
    op.drop_column("scores_justifications", "person_id")
    op.drop_table("compliance")
    # ### end Alembic commands ###
