"""empty message

Revision ID: b5e40240186d
Revises: 6ad072a15e50
Create Date: 2023-06-28 17:12:25.638238

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b5e40240186d"
down_revision = "6ad072a15e50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column(
            "application_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.Column("tag_value", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["assessment_records.application_id"],
            name=op.f("fk_tag_application_id_assessment_records"),
        ),
        sa.PrimaryKeyConstraint(
            "application_id", "tag_value", name=op.f("pk_tag")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("tag")
    # ### end Alembic commands ###
