"""empty message

Revision ID: c20eef2754cf
Revises: 91ed555648be
Create Date: 2022-07-18 16:52:27.694556

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op


# revision identifiers, used by Alembic.
revision = "c20eef2754cf"
down_revision = "91ed555648be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "criteria",
        sa.Column(
            "criteria_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column("criteria_name", sa.Text(), nullable=True),
        sa.Column("round_id", sa.String(), nullable=True),
        sa.Column("fund_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("criteria_id", name=op.f("pk_criteria")),
    )
    with op.batch_alter_table("assessment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fund_id", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("round_id", sa.Text(), nullable=True))

    with op.batch_alter_table(
        "scores_justifications", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "assessment_id",
            existing_type=sa.VARCHAR(length=255),
            nullable=False,
        )
        batch_op.alter_column(
            "assessor_user_id",
            existing_type=sa.VARCHAR(length=255),
            nullable=False,
        )
        batch_op.alter_column(
            "sub_criteria_id",
            existing_type=sa.VARCHAR(length=255),
            nullable=False,
        )
        batch_op.alter_column(
            "score", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("sub_criteria", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_sub_criteria_criteria_id_criteria"),
            "criteria",
            ["criteria_id"],
            ["criteria_id"],
        )
        batch_op.drop_column("round_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sub_criteria", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("round_id", sa.VARCHAR(length=255), nullable=True)
        )
        batch_op.drop_constraint(
            batch_op.f("fk_sub_criteria_criteria_id_criteria"),
            type_="foreignkey",
        )

    with op.batch_alter_table(
        "scores_justifications", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "score", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "sub_criteria_id",
            existing_type=sa.VARCHAR(length=255),
            nullable=True,
        )
        batch_op.alter_column(
            "assessor_user_id",
            existing_type=sa.VARCHAR(length=255),
            nullable=True,
        )
        batch_op.alter_column(
            "assessment_id",
            existing_type=sa.VARCHAR(length=255),
            nullable=True,
        )

    with op.batch_alter_table("assessment", schema=None) as batch_op:
        batch_op.drop_column("round_id")
        batch_op.drop_column("fund_id")

    op.drop_table("criteria")
    # ### end Alembic commands ###
