"""empty message

Revision ID: cd404dd517c5
Revises: 4dd55a3dc51e
Create Date: 2022-07-13 09:12:00.980796

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "cd404dd517c5"
down_revision = "4dd55a3dc51e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sub_criteria",
        sa.Column("sub_criteria_id", sa.Text(), nullable=False),
        sa.Column("round_id", sa.String(length=255), nullable=True),
        sa.Column("criteria_id", sa.String(length=255), nullable=True),
        sa.Column("sub_criteria_title", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("sub_criteria_id"),
    )
    op.create_table(
        "scores_justifications",
        sa.Column(
            "scores_justifications_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("assessment_id", sa.String(length=255), nullable=True),
        sa.Column("assessor_user_id", sa.String(length=255), nullable=True),
        sa.Column("sub_criteria_id", sa.String(length=255), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("justification", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sub_criteria_id"],
            ["sub_criteria.sub_criteria_id"],
        ),
        sa.PrimaryKeyConstraint("scores_justifications_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scores_justifications")
    op.drop_table("sub_criteria")
    # ### end Alembic commands ###
