"""added criteria

Revision ID: de12e9222848
Revises: cd404dd517c5
Create Date: 2022-07-14 11:14:29.068023

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op


# revision identifiers, used by Alembic.
revision = "de12e9222848"
down_revision = "cd404dd517c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "criteria",
        sa.Column(
            "criteria_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column("criteria_name", sa.Text(), nullable=True),
        sa.Column("round_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("criteria_id", name=op.f("pk_criteria")),
    )
    with op.batch_alter_table("sub_criteria", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_sub_criteria_criteria_id_criteria"),
            "criteria",
            ["criteria_id"],
            ["criteria_id"],
        )
        batch_op.drop_column("round_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sub_criteria", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("round_id", sa.VARCHAR(length=255), nullable=True)
        )
        batch_op.drop_constraint(
            batch_op.f("fk_sub_criteria_criteria_id_criteria"),
            type_="foreignkey",
        )

    op.drop_table("criteria")
    # ### end Alembic commands ###
