"""empty message

Revision ID: e30dc9a7e7c6
Revises: 592143492996
Create Date: 2022-07-05 16:32:42.664873

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "e30dc9a7e7c6"
down_revision = "592143492996"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scores_justifications",
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )
    op.drop_column("scores_justifications", "timestamp")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scores_justifications",
        sa.Column("timestamp", sa.TEXT(), nullable=True),
    )
    op.drop_column("scores_justifications", "created_at")
    # ### end Alembic commands ###
