"""empty message

Revision ID: e7f4ee02150b
Revises:
Create Date: 2022-07-12 16:09:39.103883

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "e7f4ee02150b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessment",
        sa.Column(
            "id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column("compliance_status", sa.Text(), nullable=True),
        sa.Column("application_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assessment_application_id"),
        "assessment",
        ["application_id"],
        unique=True,
    )
    op.create_table(
        "sub_criteria",
        sa.Column("sub_criteria_id", sa.Text(), nullable=False),
        sa.Column("round_id", sa.String(length=255), nullable=True),
        sa.Column("criteria_id", sa.String(length=255), nullable=True),
        sa.Column("sub_criteria_title", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("sub_criteria_id"),
    )
    op.create_table(
        "scores_justifications",
        sa.Column(
            "scores_justifications_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("assessment_id", sa.String(length=255), nullable=True),
        sa.Column("assessor_user_id", sa.String(length=255), nullable=True),
        sa.Column("sub_criteria_id", sa.String(length=255), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("justification", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sub_criteria_id"],
            ["sub_criteria.sub_criteria_id"],
        ),
        sa.PrimaryKeyConstraint("scores_justifications_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scores_justifications")
    op.drop_table("sub_criteria")
    op.drop_index(
        op.f("ix_assessment_application_id"), table_name="assessment"
    )
    op.drop_table("assessment")
    # ### end Alembic commands ###
