"""empty message

Revision ID: f783496def21
Revises: 5ce0b8e0e1b6
Create Date: 2022-12-01 14:59:04.914461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f783496def21'
down_revision = '5ce0b8e0e1b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('just_scores',
    sa.Column('score_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('application_id', postgresql.UUID(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('sub_criteria_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['assessment_records.application_id'], name=op.f('fk_just_scores_application_id_assessment_records')),
    sa.PrimaryKeyConstraint('score_id', name=op.f('pk_just_scores'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('just_scores')
    # ### end Alembic commands ###
