"""Adding application-store model.

Revision ID: 5f9082c024f1
Revises: eecdd097df78
Create Date: 2024-11-07 13:51:58.709734

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5f9082c024f1"
down_revision = "eecdd097df78"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("fund_id", sa.String(), nullable=False),
        sa.Column("round_id", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("language", postgresql.ENUM(name="language", create_type=False), nullable=True),
        sa.Column("reference", sa.String(), nullable=False),
        sa.Column("project_name", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("NOT_STARTED", "IN_PROGRESS", "SUBMITTED", "COMPLETED", name="application_status"),
            nullable=False,
        ),
        sa.Column("date_submitted", sa.DateTime(), nullable=True),
        sa.Column("last_edited", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint("fund_id", "round_id", "key", name="_reference"),
        sa.UniqueConstraint("reference", name=op.f("uq_applications_reference")),
    )
    op.create_table(
        "eligibility",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("form_id", sa.String(), nullable=False),
        sa.Column("answers", sa.JSON(), nullable=True),
        sa.Column("eligible", sa.Boolean(), nullable=True),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("date_submitted", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], name=op.f("fk_eligibility_application_id_applications")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eligibility")),
    )
    op.create_table(
        "end_of_application_survey_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("fund_id", sa.String(), nullable=False),
        sa.Column("round_id", sa.String(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("date_submitted", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_end_of_application_survey_feedback_application_id_applications"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_end_of_application_survey_feedback")),
        sa.UniqueConstraint("application_id", "page_number", name="_unique_application_page"),
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("fund_id", sa.String(), nullable=False),
        sa.Column("round_id", sa.String(), nullable=False),
        sa.Column("section_id", sa.String(), nullable=False),
        sa.Column("feedback_json", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("NOT_STARTED", "IN_PROGRESS", "SUBMITTED", "COMPLETED", name="feedback_status"),
            nullable=False,
        ),
        sa.Column("date_submitted", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], name=op.f("fk_feedback_application_id_applications")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
        sa.UniqueConstraint("application_id", "section_id", name=op.f("uq_feedback_application_id")),
    )
    op.create_table(
        "forms",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("json", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("NOT_STARTED", "IN_PROGRESS", "SUBMITTED", "COMPLETED", name="form_status"),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("has_completed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], name=op.f("fk_forms_application_id_applications")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forms")),
        sa.UniqueConstraint("id", "name", name=op.f("uq_forms_id")),
    )
    op.create_table(
        "research_survey",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("fund_id", sa.String(), nullable=False),
        sa.Column("round_id", sa.String(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("date_submitted", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"], ["applications.id"], name=op.f("fk_research_survey_application_id_applications")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_survey")),
        sa.UniqueConstraint("application_id", name=op.f("uq_research_survey_application_id")),
    )
    with op.batch_alter_table("assessment_records", schema=None) as batch_op:
        batch_op.create_index(
            "ix_jsonb_blob_nURkuc", [sa.text("(jsonb_blob -> 'nURkuc')")], unique=False, postgresql_using="gin"
        )

    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index("value_round_id_unique_idx")
        batch_op.create_index("tag_value_round_id_ix", [sa.text("lower(value)"), "round_id"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index("tag_value_round_id_ix")
        batch_op.create_index("value_round_id_unique_idx", [sa.text("lower(value::text)"), "round_id"], unique=True)

    with op.batch_alter_table("assessment_records", schema=None) as batch_op:
        batch_op.drop_index("ix_jsonb_blob_nURkuc", postgresql_using="gin")

    op.drop_table("research_survey")
    op.drop_table("forms")
    op.drop_table("feedback")
    op.drop_table("end_of_application_survey_feedback")
    op.drop_table("eligibility")
    op.drop_table("applications")
    # ### end Alembic commands ###
