"""Empty message.

Revision ID: fe032b385f53
Revises: eecdd097df78
Create Date: 2024-10-24 11:40:48.868362

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fe032b385f53"
down_revision = "eecdd097df78"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    insert_query = sa.text(
        "INSERT INTO assessment_round(round_id, scoring_system_id)"
        "VALUES (:uuid, :scoring_system_id) RETURNING round_id;"
    )

    params = {
        "uuid": "9104d809-0fb0-4144-b514-55e81cc2b6fa",
        "scoring_system_id": "80c18412-d6a2-439a-89b7-379d7a4e7573",
    }
    connection.execute(insert_query, params)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    delete_query = sa.text("DELETE FROM assessment_round WHERE round_id = :uuid;")
    params = {
        "uuid": "9104d809-0fb0-4144-b514-55e81cc2b6fa",
    }
    connection.execute(delete_query, params)
    # ### end Alembic commands ###
