"""Empty message.

Revision ID: 2737a83d7605
Revises: cf1169998c27
Create Date: 2024-07-02 13:35:20.268046

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2737a83d7605"
down_revision = "cf1169998c27"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("allocation_association", schema=None) as batch_op:
        batch_op.add_column(sa.Column("assigner_id", sa.UUID(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("allocation_association", schema=None) as batch_op:
        batch_op.drop_column("assigner_id")

    # ### end Alembic commands ###
