"""Inserting scoring_system ZeroToOne.

Revision ID: c0fd614c99ea
Revises: 94b31619f50a
Create Date: 2024-05-09 18:07:40.734667

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c0fd614c99ea"
down_revision = "94b31619f50a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    insert_query = sa.text(
        "INSERT INTO assessment_round(round_id, scoring_system)" "VALUES (:uuid, :scoring_system) RETURNING round_id;"
    )

    params = {
        "uuid": "50062ff6-e696-474d-a560-4d9af784e6e5",
        "scoring_system": "ZeroToOne",
    }
    connection.execute(insert_query, params)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    delete_query = sa.text("DELETE FROM assessment_round WHERE round_id = :uuid;")
    params = {
        "uuid": "50062ff6-e696-474d-a560-4d9af784e6e5",
    }
    connection.execute(delete_query, params)
    # ### end Alembic commands ###
