"""Add `comments_update` table.

Revision ID: f0625240974a
Revises: 482f385dd1ee
Create Date: 2023-11-10 11:09:45.918590

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f0625240974a"
down_revision = "482f385dd1ee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments_update",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("comment_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column(
            "date_created",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.comment_id"],
            name=op.f("fk_comments_update_comment_id_comments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments_update")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comments_update")
    # ### end Alembic commands ###
