"""Empty message.

Revision ID: 3634979d3b07
Revises: 55f4ac45dd50
Create Date: 2024-11-21 23:34:08.253443

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3634979d3b07"
down_revision = "55f4ac45dd50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("flag_update", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.VARCHAR(), nullable=True)

    op.execute("DROP TRIGGER IF EXISTS block_updates_on_app_blob on assessment_records")

    op.execute("alter type status add value 'APPLICATION_UPDATED' after 'COMPLETED'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("flag_update", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
