name: Deploy and Test (AWS)

on:
  workflow_dispatch:
    inputs:
      deploy_to_dev:
        required: false
        default: false
        type: boolean
        description: Deploy to dev?
  push:
    paths-ignore:
      - '**/README.md'

jobs:
  paketo_build:
    permissions:
      packages: write
    uses: communitiesuk/funding-design-service-workflows/.github/workflows/package.yml@main
    with:
      version_to_build: $(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
      owner: ${{ github.repository_owner }}
      application: funding-service-design-assessment-store
  test_and_deploy_aws:
    uses: communitiesuk/funding-design-service-workflows/.github/workflows/deploy-aws.yml@FS-3337-split-aws-deploy
    needs: paketo_build
    with:
      app_name: ${{ github.event.repository.name }}
      api: true
      postgres_unit_testing: true
      db_name: fsd_assess_store_test
      deploy_to_dev: ${{github.event.inputs.deploy_to_dev == 'true'}}
      run_performance_tests: true
      run_e2e_tests: true
