name: Zap Scan
on:
  workflow_dispatch:
  jobs:
    zap_scan:
      runs-on: ubuntu-latest
      environment: Dev
      steps:
        - name: checkout code
          uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.10.1
        - name: install dependencies
          run: python -m pip install --upgrade pip && python -m pip install -r requirements.txt
        - name: ZAP Scan
          uses: zaproxy/action-full-scan@v0.3.0
          with:
            target: 'https://${{inputs.app_name}}-dev.london.cloudapps.digital/'
            allow_issue_writing: False
